use openjdk:9-jre instead of openjdk:8-jre to avoid `java.lang.NoSuchMethodError: java.nio.ByteBuffer.flip()Ljava/nio/ByteBuffer`.
Seems to be an issue with Knox being compiled with Java 9 but targeting Java 8 w/o using the correct `--release 8` command line argument.